name: Manual Service Job
on:
  workflow_dispatch:
    inputs:
      service_name:
            description: 'Choose either "frontend" or "backend" to build'
            required: true
            default: 'frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ github.event.inputs.service_name }}/
          file: ./${{ github.event.inputs.service_name }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/moon-${{ github.event.inputs.service_name }}:${{ github.run_number }}
      -
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      -
        name: Update kubeconfig
        run: aws eks update-kubeconfig --name moon
      -
        name: Deploy micro-service with helm chart
        run: |
          helm upgrade --install ${{ github.event.inputs.service_name }} ./${{ github.event.inputs.service_name }}/helm --set image.tag=${{ github.run_number }} --wait --kubeconfig /home/runner/.kube/config
      -
        name: Run health check with helm test
        run: |
          sleep 5 &&
          helm test ${{ github.event.inputs.service_name }}